### PR TITLE
Update Config.json

### PR DESCRIPTION
**Pull request by Erenulla**
test

### CODE REVIEW

**Comment by justkorudev** [comment]
@Erenulla please change your bot token, you just leaked it.

**Comment by drizzle-mizzle** [comment]
> @Erenulla please change your bot token, you just leaked it.

Usually, Discord drops it automatically in the very moment it being published on GitHub

**Comment by drizzle-mizzle** [comment]
Don't wanna delete this PR, it's so funny

**Comment by justkorudev** [comment]
> > @Erenulla please change your bot token, you just leaked it.
> 
> Usually, Discord drops it automatically in the very moment it being published on GitHub

Still, just for safety

**Comment by justkorudev** [comment]
> Don't wanna delete this PR, it's so funny 
> 
> 

XD

**Pull request closed without merging**
